
import streamlit as st

def app():
    st.markdown("# Covid Forecasting Joint Learning")
    st.markdown("This is an undergraduate thesis project. This web app is a quick prototype based on the project's ipython notebooks, powered by Streamlit. Despite being a web app, this is meant for offline and personal use.")
    abstract_expander = st.expander(label='Abstract', expanded=True)
    with abstract_expander:
        st.markdown("## Abstract")
        st.markdown("COVID-19 is a dangerous illness because it spreads quickly and easily. Vaccines are already available but the pandemic isn’t likely to end quick. Forecasting is hoped to help handle the pandemic. Deep learning, specially LSTM, has been used to forecast COVID-19 case count in some regions. However, deep learning models need a lot of data while COVID-19 daily data are scarce. Still, COVID-19 doesn’t happen in just one region but also in neighboring regions. This research aims to use joint learning with data from other regions to improve model performance with fewer data and to use the model to forecast until 9 months since the date of last data taken. Joint learning is done by making models share some modules and training the models together. To overcome the different data scale and pandemic age in the regions, the data was first transformed into SIRD variables and was evaluated using RMSSE. Joint learning failed to improve the model performance in this research. The proposed model performance is better than ARIMA-SIRD and SIRD model but isn’t better than normal encoder-decoder LSTM and only reaches RMSSE below one occasionally. Pandemic in Kab. Sampang, Kab. Tuban, Kota Madiun, and Kota Pasuruan which are in the same cluster were forecasted to end quickly in May 2021, while the active case count in Kab. Bojonegoro was forecasted to increase drastically in June 2021 to its peak in late July after infecting 78.48% of the population. All of those forecasts are way off because the models were only trained to forecast 14 days ahead and there was the new delta variant which weren’t in the training data. Solely for Kab. Bojonegoro, the model captured the shape pretty well, although the scale is way off.")